version: "3"
services:
  atomization:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
      - $PWD:/root
    working_dir: /root
    entrypoint: ["bash"]
    stdin_open: true
    tty: true
