[project]
name = "atomization"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mysql-connector-python",
    "coqpyt"
]

[project.scripts]
main = "atomization.atomizer:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/atomization"]

[tool.uv.sources]
coqpyt = { git = "https://github.com/sr-lab/coqpyt" }
