FROM nixos/nix:latest AS nix-builder

# Enable experimental features for Nix to use flakes
RUN echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

# Sanity check
RUN nix --version && nix shell nixpkgs#neofetch -c "neofetch"
