FROM nixos/nix:latest AS nix-builder

# Enable experimental features for Nix to use flakes
RUN nix-env -iA nixpkgs.nixFlakes \
    && echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

RUN nix --version && nix shell nixpkgs#neofetch -c "neofetch"
