name: CI with Python and Lean
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Lean setup and build first
      - name: Install elan (Lean version manager)
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Build Lean project
        run: |
          cd examples/lean
          elan toolchain install leanprover/lean4:v4.16.0-rc1
          lake build
      - name: Install Isabelle
        run: |
          mkdir -p ~/isabelle
          cd ~/isabelle
          wget https://isabelle.in.tum.de/dist/Isabelle2025_linux.tar.gz
          tar -xzf Isabelle2025_linux.tar.gz
          echo "$(cd ~/isabelle/Isabelle2025 && pwd)/bin" >> $GITHUB_PATH
          ~/isabelle/Isabelle2025/bin/isabelle version

      # Python setup and tests after Lean is built
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: Install packages
        run: |
          uv sync
      - name: Check lint
        run: uv run ruff check .
      - name: Run tests
        run: |
          uv run test
