name: CI with Python and Lean
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  python-checks-tests:
    name: Python lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: Install packages
        run: |
          uv sync
      - name: Check lint
        run: uv run ruff check .
      - name: Run tests
        run: |
          uv run test

  lean-checks:
    name: Lean build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Lean
        uses: leanprover/lean-action@v1
        with:
          # Automatically configure based on the Lake workspace
          auto-config: true
          # Enable building, testing, and linting
          build: true
          test: true
          lint: true
          # Enable GitHub caching for faster CI runs
          use-github-cache: true
